### PR TITLE
Apptool launch

### PR DESCRIPTION
**Pull request by garyluu**
For start of SEAB-3732

Had a really tough time changing things back and forth trying to figure out what to do.

Current plan is to just have the apptool run in workflow mode while specifically mentioning the oddity in the launch tab.

Here's the very start of the plan. I didn't create a new class or refactor any existing code. It's kind of a mess right now and not entirely sure if this is the way to proceed.

https://docs.google.com/document/d/12q1FH_fbFd9ZqL09PaRuqwJUptghfFgOBcQH9AE6ngA/edit?usp=sharing

Another option is the create an entry mode (./dockstore entry launch) that would be more ambitious and would require a lot of rework

Only the CWL launch with commands have been tested with this PR. will proceed with everything else after approval

TODO: create another endpoint on the webservice so I don't have to run through up to 4 endpoints to get the workflow/apptool

### CODE REVIEW

**Comment by coverbeck** [comment]
Can entry names ever clash? I know Natalie added code to prevent app tools from clashing with workflows, are there any other possibilities?

My order of preference, ignoring implementation difficulty:

1. dockstore entry - assuming there are no name clashes
2. dockstore tool - from the end user perspective, it's a tool, even though it's internally implemented it as a workflow.

**Comment by garyluu** [comment]
> Can entry names ever clash? I know Natalie added code to prevent app tools from clashing with workflows, are there any other possibilities?
> 
> My order of preference, ignoring implementation difficulty:
> 
> 1. dockstore entry - assuming there are no name clashes
> 2. dockstore tool - from the end user perspective, it's a tool, even though it's internally implemented it as a workflow.

1. I don't think the entry names can clash. and if it can, we should probably find a way to prevent that.
2. Ya, it is odd that we make the distinction that something is a tool or workflow. The docs link mentions the difficulties of trying to force a workflow into the toolclient. I suspect reworking it would be almost on par with the entry command.

**Comment by NatalieEO** [comment]
> Can entry names ever clash? I know Natalie added code to prevent app tools from clashing with workflows, are there any other possibilities?
> 
Does the CLI do services? The entry name right now could clash with services, but the same work I did to prevent name clashing between workflows and tools should be easy to add to services as well. Tools as we have them now in production should never clash since they would never start with "github.com"

**Comment by garyluu** [comment]
> 

The CLI makes no mention of services so probably not

**Comment by NatalieEO** [comment]
Should we have a broader discussion about whether we want to eventually get rid of tools? Or have some other distinction...eg distinguish types by whether it's docker image based or descriptor file based.

**Comment by garyluu** [comment]
> Should we have a broader discussion about whether we want to eventually get rid of tools? Or have some other distinction...eg distinguish types by whether it's docker image based or descriptor file based. That should make the UI a lot less messy than what it is now...

Should probably discuss further. But to me, nothing is _really_ based on Docker image. It's supposed to be based on the descriptor file. The presence of a specified Docker image only makes it more problematic.

**Review by coverbeck — COMMENTED** [review]
Was here, waiting for next iteration based on discussion

**Pull request closed without merging**
