### PR TITLE
merge Release/1.11.0 to develop

### PR DESCRIPTION
**Pull request by wshands**

### CODE REVIEW

**Review by denis-yuen — COMMENTED** [review]
Looks like legit build issues. LGTM sees merge conflicts, Circle CI has issues with the licenses file

**Review by coverbeck — APPROVED** [review]

**Review by denis-yuen — COMMENTED** [review]
Isn't LGTM still showing merge conflicts?

**Comment by coverbeck** [comment]
> Isn't LGTM still showing merge conflicts?

Oh, that's odd, I'd overlooked that. Curious because GitHub doesn't show any conflicts.

**Review by garyluu — APPROVED** [review]

**Review by denis-yuen — CHANGES_REQUESTED** [review]
> > Isn't LGTM still showing merge conflicts?
> 
> Oh, that's odd, I'd overlooked that. Curious because GitHub doesn't show any conflicts.

Do you see something different from this?

Screenshot from 2021-07-14 15-50-22

**Comment by coverbeck** [comment]
> > Oh, that's odd, I'd overlooked that. Curious because GitHub doesn't show any conflicts.
> 
> Do you see something different from this?

I see them. I must have overlooked.

**Comment by wshands** [comment]
For some reason the conflicts were not reported on this page until just recently...

**Review by denis-yuen — APPROVED** [review]

**Review by Richard-Hansen — APPROVED** [review]

**Review by NatalieEO — APPROVED** [review]

**Pull request merged**
