### PR TITLE
merge Release/1.11.0 into master

### PR DESCRIPTION
**Pull request by wshands**

### CODE REVIEW

**Review by garyluu — COMMENTED** [review]
I was here, conflicts

**Review by coverbeck — CHANGES_REQUESTED** [review]
Was here... there are a bunch of merge conflicts. I had thought they were just for LGTM, but PR itself shows a bunch.

**Review by denis-yuen — CHANGES_REQUESTED** [review]
Ditto on merge conflicts?

**Comment by wshands** [comment]
Will make a copy of release/1.11.0 and merge that to master; because I will merge release/1.11.0 to develop first and so must resolve conflicts with develop first which will alter release/1.11.0

**Pull request closed without merging**
